#!/usr/bin/with-contenv bash

source /tmp/cloud_run_ssh.env

if [[ "${SSH_CONTENT_FLAVOR}" == "dev" ]]; then
  export PORT="${PORT:-8888}"
elif [[ "${SSH_CONTENT_FLAVOR}" == "app" ]]; then
  export PORT="${PORT:-8888}"
else
  export PORT="${PORT:-$WEBSSH_PORT}"
fi

printenv

trap 'kill -TERM $SUPERVISOR_PID' TERM INT
supervisord --configuration=/svc.conf &
export SUPERVISOR_PID=$!
echo "[INFO] – Supervisor started w/PID: ${SUPERVISOR_PID}"
wait ${SUPERVISOR_PID}
trap - TERM INT
wait ${SUPERVISOR_PID}
echo "[INFO] – Supervisor ( PID: ${SUPERVISOR_PID} ) exited"

# https://github.com/just-containers/s6-overlay?tab=readme-ov-file#writing-a-service-script
/run/s6/basedir/bin/halt
