steps:
  - id: "build image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--file=Dockerfile.full'
      - '-t'
      - '${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '--build-arg=CLOUDSDK_VERSION=${_CLOUDSDK_VERSION}'
      - '--build-arg=CSQL_PROXY_VERSION=${_CSQL_PROXY_VERSION}'
      - '--build-arg=ALLOYDB_PROXY_VERSION=${_ALLOYDB_PROXY_VERSION}'
      - '--build-arg=USQL_VERSION=${_USQL_VERSION}'
      - '--build-arg=GCSFUSE_VERSION=${_GCSFUSE_VERSION}'
      - '--build-arg=WEB_PORT=${_WEB_PORT}'
      - '--build-arg=SSH_USER=${_SSH_USER}'
      - '--build-arg=SSH_PASS=${_SSH_PASS}'
      - '.'
images: ['${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}']
substitutions:
  # http://cloud/sdk/docs/release-notes ( i/e: 437.0.1 )
  _CLOUDSDK_VERSION: 459.0.0
  # https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases ( i/e: 2.4.0 )
  _CSQL_PROXY_VERSION: 2.8.1
  # https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/releases ( i/e: 1.3.0 )
  _ALLOYDB_PROXY_VERSION: 1.6.1
  # https://github.com/xo/usql/releases ( i/e: 0.14.8 )
  _USQL_VERSION: 0.17.5
  _GCSFUSE_VERSION: 2.1.0
  _WEB_PORT: '8080' # Choose a port
  _SSH_USER: 'user' # Choose a username
  _SSH_PASS: 'pass' # Choose a password
tags: ['ssh', '${_BUILD_TAG}']
