steps:
  - id: "build ssh-server image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "buildx"
      - "build"
      - "--no-cache"
      - "--platform=linux/amd64"
      - "--file=${_DOCKERFILE}"
      - "--tag"
      - "${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}"
      - "--build-arg=WEB_PORT=${_WEB_PORT}"
      - "--build-arg=SSH_USER=${_SSH_USER}"
      - "--build-arg=SSH_PASS=${_SSH_PASS}"
      - "--build-arg=CLOUDSDK_VERSION=${_CLOUDSDK_VERSION}"
      - "--build-arg=GCSFUSE_VERSION=${_GCSFUSE_VERSION}"
      - "--build-arg=CSQL_PROXY_VERSION=${_CSQL_PROXY_VERSION}"
      - "--build-arg=ALLOYDB_PROXY_VERSION=${_ALLOYDB_PROXY_VERSION}"
      - "--build-arg=USQL_VERSION=${_USQL_VERSION}"
      - "."
images:
  [
    "${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}",
  ]
tags: ["cloud-run", "ssh", "${_BUILD_TAG}"]
