- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    # https://cloud.google.com/sdk/docs/release-notes ( i/e: 455.0.0 )
    - --build-arg
    - CLOUDSDK_VERSION=455.0.0
    # https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases ( i/e: 2.4.0 )
    - --build-arg
    - CSQL_PROXY_VERSION=2.4.0
    # https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/releases ( i/e: 1.3.0 )
    - --build-arg
    - ALLOYDB_PROXY_VERSION=1.3.0
    # https://github.com/xo/usql/releases ( i/e: 0.14.8 )
    - --build-arg
    - USQL_VERSION=0.14.8
    - --build-arg
    - USER_NAME=test
    - --build-arg
    - USER_PASSWORD=test
    - --build-arg
    - SERVICE_PORT=8080
    - --tag
    - us-docker.pkg.dev/chux-testing/serverless/ssh
