#!/bin/bash

set -x

source $(pwd)/.env

DOCKER_LOCAL_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
DOCKER_REMOTE_IMAGE="${IMAGE_URI_BASE}/${DOCKER_LOCAL_IMAGE}"

docker buildx build --no-cache \
  --platform=linux/amd64 \
  --file=$(pwd)/Dockerfile.${IMAGE_TAG} \
  --tag=${DOCKER_LOCAL_IMAGE} \
  --build-arg="GCSFUSE_VERSION=${GCSFUSE_VERSION}" \
  --build-arg="CLOUDSDK_VERSION=${CLOUDSDK_VERSION}" \
  --build-arg="CSQL_PROXY_VERSION=${CSQL_PROXY_VERSION}" \
  --build-arg="ALLOYDB_PROXY_VERSION=${ALLOYDB_PROXY_VERSION}" \
  --build-arg="USQL_VERSION=${USQL_VERSION}" \
  --label="GCSFUSE_VERSION=v${GCSFUSE_VERSION}" \
  --label="CLOUDSDK_VERSION=v${CLOUDSDK_VERSION}" \
  --label="CSQL_PROXY_VERSION=v${CSQL_PROXY_VERSION}" \
  --label="ALLOYDB_PROXY_VERSION=v${ALLOYDB_PROXY_VERSION}" \
  --label="USQL_VERSION=v${USQL_VERSION}" \
  --build-arg="SSH_USER=${SSH_USER}" \
  --build-arg="SSH_PASS=${SSH_PASS}" \
  --build-arg="WEB_PORT=${WEB_PORT}" \
  $(pwd)

docker tag ${DOCKER_LOCAL_IMAGE} ${DOCKER_REMOTE_IMAGE}
docker push ${DOCKER_REMOTE_IMAGE}
