#! /bin/bash

SSH_HOST='127.0.0.1'
SSH_PORT='2222'


JQ_CMD='/yq -M -pj -oj -I0'

DEFAULT_SSH_PROXY_SERVER_API_PORT=5000
DEFAULT_SSH_PROXY_SERVER_TUNNEL_PORT=5555

export EXPECTED_SSH_PROXY_SERVER_NAME="${SSH_PROXY_SERVER_ID}.ssh-proxy.internal"

# make sure that INGRESS is created agains the correct SSH Proxy Server: get the subject from the SSH Proxy Server self-signed certificate.
export SSH_PROXY_SERVER_API_HOST_AND_PPORT="${SSH_PROXY_SERVER_HOST}:${SSH_PROXY_SERVER_API_PORT:-$DEFAULT_SSH_PROXY_SERVER_API_PORT}"
export SSH_PROXY_SERVER_NAME=`openssl s_client -connect "${SSH_PROXY_SERVER_API_HOST_AND_PPORT}" 2>&1 </dev/null | grep 'subject=' | tr -d ' ' | tr ',' '\n' | grep -Ei '^CN=.*' | awk -F'=' '{print $2}' | tr -d '\n'`

if [[ "${SSH_PROXY_SERVER_NAME}" != "${EXPECTED_SSH_PROXY_SERVER_NAME}" ]]; then
  echo "SSH Proxy Server identity could not be verified: ${EXPECTED_SSH_PROXY_SERVER_NAME} - ${SSH_PROXY_SERVER_NAME}"
  exit 0
fi

MDS_URL='http://metadata.google.internal/computeMetadata/v1'
MDS_IDENTITY_PATH='instance/service-accounts/default/identity'
MDS_ID_TOKEN_CURL="curl -s -H Metadata-Flavor:Google ${MDS_URL}/${MDS_IDENTITY_PATH}?audience=${SSH_PROXY_SERVER_NAME}&format=full"

ID_TOKEN="$(${MDS_ID_TOKEN_CURL} | tr -d '\n')"

SSH_PROXY_SERVER_API_URL="https://${SSH_PROXY_SERVER_API_HOST_AND_PPORT}/instance/${INSTANCE_ID}"
SERVERLESS_INSTANCE=`curl -sk -H "x-s8s-ssh-authorization: ${ID_TOKEN}" -H "x-s8s-ssh-server-id: ${SSH_PROXY_SERVER_ID}" "${SSH_PROXY_SERVER_API_URL}" | ${JQ_CMD} 'del(.instance,.ping)' | tr -d '\n'`

echo "${SERVERLESS_INSTANCE}" | /yq -pj -os -rM 'del(.tunnel)'

SSH_PROXY_CLIENT_ID=`echo "${SERVERLESS_INSTANCE}" | /yq -pj -oa -rM '.tunnel' | tr -d '\n'`
echo "Discovered tunnel '${SSH_PROXY_CLIENT_ID}' for instance '${INSTANCE_ID}'":

sed -e "s|%SSH_PROXY_SERVER_HOST%|${SSH_PROXY_SERVER_HOST}|g" \
  -e "s|%SSH_PROXY_SERVER_TUNNEL_PORT%|${SSH_PROXY_SERVER_TUNNEL_PORT:-$DEFAULT_SSH_PROXY_SERVER_TUNNEL_PORT}|g" \
  -e "s|%SSH_PROXY_SERVER_ID%|${SSH_PROXY_SERVER_ID}|g" \
  -e "s|%SSH_PROXY_CLIENT_ID%|${SSH_PROXY_CLIENT_ID}|g" \
  -e "s|%PROJECT_ID%|${PROJECT_ID}|g" \
  -e "s|%INSTANCE_ID%|${INSTANCE_ID}|g" \
  /ssh_proxy_visitor.yaml > /tmp/ssh_proxy_visitor.yaml

/gost -C /tmp/ssh_proxy_visitor.yaml &>/dev/null &

while : ; do
  proxy_available=`netstat -tulpan 2>/dev/null | grep -i listen | grep ':2222' | grep tcp6 | sort | uniq | wc -l | tr -d '\n'`
  [[ "${proxy_available}" == '1' ]] && break
  echo "waiting for proxy..."
  sleep 1
done

sleep 1

if [[ -s "/ssh.key" ]]; then
  ssh -v -p ${SSH_PORT} -i /ssh.key root@${SSH_HOST}
else
  ssh -v -p ${SSH_PORT} root@${SSH_HOST}
fi
