#! /bin/bash

DEFAULT_SSH_PROXY_SERVER_API_PORT=5000
DEFAULT_SSH_PROXY_SERVER_TUNNEL_PORT=5555
DEFAULT_SSH_PROXY_SERVER_PORT=5050
DEFAULT_SSH_PROXY_SERVER_ID='00000000-0000-0000-0000-000000000000'

sed -e "s|%SSH_PROXY_SERVER_API_PORT%|${SSH_PROXY_SERVER_API_PORT:-$DEFAULT_SSH_PROXY_SERVER_API_PORT}|g" \
  -e "s|%SSH_PROXY_SERVER_TUNNEL_PORT%|${SSH_PROXY_SERVER_TUNNEL_PORT:-$DEFAULT_SSH_PROXY_SERVER_TUNNEL_PORT}|g" \
  -e "s|%SSH_PROXY_SERVER_PORT%|${SSH_PROXY_SERVER_PORT:-$DEFAULT_SSH_PROXY_SERVER_PORT}|g" \
  -e "s|%SSH_PROXY_SERVER_ID%|${SSH_PROXY_SERVER_ID:-$DEFAULT_SSH_PROXY_SERVER_ID}|g" \
  -e "s|%SSH_PROXY_SERVER_ID%|${SSH_PROXY_SERVER_ID:-$DEFAULT_SSH_PROXY_SERVER_ID}|g" \
  -e "s|%PROJECT_ID%|${PROJECT_ID}|g" \
  /ssh_proxy_server.yaml > /tmp/_ssh_proxy_server.yaml

/yq -M '. *= load("/tmp/_ssh_proxy_server.yaml")' \
  <(/yq '{"admissions": [{"name": "allowed-hosts", "whitelist": true, "matchers": .access_control.allowed_hosts}]}' /etc/ssh_proxy_server/config.yaml) \
  > /tmp/ssh_proxy_server.yaml

cat -n /tmp/ssh_proxy_server.yaml

/ssh_proxy_server &
export SSH_PROXY_SERVER_API_PID=$!

trap 'kill -TERM $SSH_PROXY_SERVER_PID' TERM INT
/gost -D -C /tmp/ssh_proxy_server.yaml 2>&1 | /yq -pj -oj -M &
export SSH_PROXY_SERVER_PID=$!
echo "[INFO] – SSH proxy server started w/PID: ${SSH_PROXY_SERVER_PID}"
wait ${SSH_PROXY_SERVER_PID}
trap - TERM INT
wait ${SSH_PROXY_SERVER_PID}
echo "[INFO] – SSH proxy server ( PID: ${SSH_PROXY_SERVER_PID} ) exited"

kill -15 ${SSH_PROXY_SERVER_API_PID}
